apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend

patches:
  - target:
      kind: Deployment
      name: frontend
      namespace: mindset-app  # ✅ Changed from "study-app"
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: DEBUG
            value: "true"
          - name: API_URL
            value: "http://dev-backend:22112"