apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindset-app-root
  namespace: argocd
  labels:
    app: mindset-app-bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tim275/mindset-app-gitops
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
