# /workspaces/devops-projekt/mindset-app-gitops/root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindset-app-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tim275/mindset-app-gitops
    targetRevision: HEAD
    path: appsets  # ← Zeigt auf appsets/ Verzeichnis
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true