apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/tim275/study-app-backend:latest  # ← Full image name!
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///data/sessions.db"
