# kubernetes/manifests/base/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mindset-app  # ✅ MUSS GEÄNDERT WERDEN von "study-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/tim275/study-app-backend:latest
          ports:
            - containerPort: 22112
          env:
            - name: CSV_FILE_PATH
              value: "/app/data/sessions.csv"
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"