apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mindset-app  # ✅ Changed from "study-app"
spec:
  selector:
    component: frontend
  ports:
    - port: 22111
      targetPort: 22111
  type: LoadBalancer