apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: mindset-app-prod
namePrefix: prod-
images:
  - name: ghcr.io/tim275/study-app-backend # ← Full image name wie Mischa!
    newTag: backend-v0.11.3
  - name: ghcr.io/tim275/study-app-frontend # ← Full image name wie Mischa!
    newTag: frontend-v0.12.0
