apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: mindset-app-prod # ✅ Fixed: production namespace
namePrefix: prod- # ✅ Fixed: production prefix
images:
  - name: backend
    newTag: latest # ✅ Fixed: production tag
  - name: frontend
    newTag: latest # ✅ Fixed: production tag
