# kubernetes/manifests/base/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: study-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: backend:latest      # ⚠️ Wird zu backend:dev überschrieben
          ports:
            - containerPort: 22112   # FastAPI Port (aus Dockerfile)
          env:                       # Environment für Backend
            - name: CSV_FILE_PATH
              value: "/app/data/sessions.csv"
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"