# kubernetes/manifests/base/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                     # Sammelt alle Frontend-Manifeste
  - deployment.yaml
  - service.yaml