apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: mindset-app        
namePrefix: dev-
images:
  - name: ghcr.io/tim275/study-app-backend 
    newTag: backend-v0.11.3
  - name: ghcr.io/tim275/study-app-frontend 
    newTag: frontend-v0.12.3