apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mindset-app-environments
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - env: dev
        namespace: mindset-app
        autoSync: "true"
      - env: prod
        namespace: mindset-app-prod
        autoSync: "false"
  template:
    metadata:
      name: 'mindset-app-{{.env}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/mindset-app-gitops
        targetRevision: HEAD
        path: 'apps/{{.env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    {{if eq .autoSync "true"}}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    {{end}}