apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mindset-app-environments           # Name des ApplicationSets
  namespace: argocd                        # ArgoCD Namespace
spec:
  generators:
  - list:
      elements:
      # --- DEV Environment ---
      - env: dev                          # Environment-Name (entspricht apps/dev)
        namespace: mindset-app            # Namespace f端r DEV (siehe apps/dev/namespace.yaml)
        autoSync: true                    # DEV wird automatisch synchronisiert (Auto-Deploy)
      # --- PROD Environment ---
      - env: prod                         # Environment-Name (entspricht apps/prod)
        namespace: mindset-app-prod       # Namespace f端r PROD (siehe apps/prod/namespace.yaml)
        autoSync: false                   # PROD muss manuell synchronisiert werden (PR/Approval)
  template:
    metadata:
      name: 'mindset-app-{{env}}'         # App-Name: mindset-app-dev / mindset-app-prod
      labels:
        app: mindset-app
        environment: '{{env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/mindset-app-gitops
        targetRevision: HEAD
        path: 'apps/{{env}}'              # Zeigt auf apps/dev oder apps/prod
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'        # Ziel-Namespace (dev/prod)
      syncPolicy:
        syncOptions:
        - CreateNamespace=true            # Namespace wird automatisch erstellt
        {{#autoSync}}
        automated:                        # Nur f端r DEV: Auto-Sync aktivieren
          prune: true
          selfHeal: true
        {{/autoSync}}                     # F端r PROD: Kein Auto-Sync (manuelle Freigabe)