apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mindset-app-environments
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: mindset-app
        autoSync: true        # ✅ Boolean statt String
      - env: prod
        namespace: mindset-app-prod
        autoSync: false       # ✅ Boolean statt String
  template:
    metadata:
      name: 'mindset-app-{{env}}'
      labels:
        app: mindset-app
        environment: '{{env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/mindset-app-gitops
        targetRevision: HEAD
        path: 'apps/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        {{#autoSync}}
        automated:
          prune: true
          selfHeal: true
        {{/autoSync}}